using System;
using System.Collections.Generic;
using System.Text;

namespace UnitTests.Models
{
    public class PerformanceTest
    {
        public string p1 { get; set; }="test";
        public string p2 { get; set; }="test";
        public string p3 { get; set; }="test";
        public string p4 { get; set; }="test";
        public string p5 { get; set; }="test";
        public string p6 { get; set; }="test";
        public string p7 { get; set; }="test";
        public string p8 { get; set; }="test";
        public string p9 { get; set; }="test";
        public string p10 { get; set; }="test";
        //public string p11 { get; set; }="test";
        //public string p12 { get; set; }="test";
        //public string p13 { get; set; }="test";
        //public string p14 { get; set; }="test";
        //public string p15 { get; set; }="test";
        //public string p16 { get; set; }="test";
        //public string p17 { get; set; }="test";
        //public string p18 { get; set; }="test";
        //public string p19 { get; set; }="test";
        //public string p20 { get; set; }="test";
        //public string p21 { get; set; }="test";
        //public string p22 { get; set; }="test";
        //public string p23 { get; set; }="test";
        //public string p24 { get; set; }="test";
        //public string p25 { get; set; }="test";
        //public string p26 { get; set; }="test";
        //public string p27 { get; set; }="test";
        //public string p28 { get; set; }="test";
        //public string p29 { get; set; }="test";
        //public string p30 { get; set; }="test";
        //public string p31 { get; set; }="test";
        //public string p32 { get; set; }="test";
        //public string p33 { get; set; }="test";
        //public string p34 { get; set; }="test";
        //public string p35 { get; set; }="test";
        //public string p36 { get; set; }="test";
        //public string p37 { get; set; }="test";
        //public string p38 { get; set; }="test";
        //public string p39 { get; set; }="test";
        //public string p40 { get; set; }="test";
        //public string p41 { get; set; }="test";
        //public string p42 { get; set; }="test";
        //public string p43 { get; set; }="test";
        //public string p44 { get; set; }="test";
        //public string p45 { get; set; }="test";
        //public string p46 { get; set; }="test";
        //public string p47 { get; set; }="test";
        //public string p48 { get; set; }="test";
        //public string p49 { get; set; }="test";
        //public string p50 { get; set; }="test";
        //public string p51 { get; set; }="test";
        //public string p52 { get; set; }="test";
        //public string p53 { get; set; }="test";
        //public string p54 { get; set; }="test";
        //public string p55 { get; set; }="test";
        //public string p56 { get; set; }="test";
        //public string p57 { get; set; }="test";
        //public string p58 { get; set; }="test";
        //public string p59 { get; set; }="test";
        //public string p60 { get; set; }="test";
        //public string p61 { get; set; }="test";
        //public string p62 { get; set; }="test";
        //public string p63 { get; set; }="test";
        //public string p64 { get; set; }="test";
        //public string p65 { get; set; }="test";
        //public string p66 { get; set; }="test";
        //public string p67 { get; set; }="test";
        //public string p68 { get; set; }="test";
        //public string p69 { get; set; }="test";
        //public string p70 { get; set; }="test";
        //public string p71 { get; set; }="test";
        //public string p72 { get; set; }="test";
        //public string p73 { get; set; }="test";
        //public string p74 { get; set; }="test";
        //public string p75 { get; set; }="test";
        //public string p76 { get; set; }="test";
        //public string p77 { get; set; }="test";
        //public string p78 { get; set; }="test";
        //public string p79 { get; set; }="test";
        //public string p80 { get; set; }="test";
        //public string p81 { get; set; }="test";
        //public string p82 { get; set; }="test";
        //public string p83 { get; set; }="test";
        //public string p84 { get; set; }="test";
        //public string p85 { get; set; }="test";
        //public string p86 { get; set; }="test";
        //public string p87 { get; set; }="test";
        //public string p88 { get; set; }="test";
        //public string p89 { get; set; }="test";
        //public string p90 { get; set; }="test";
        //public string p91 { get; set; }="test";
        //public string p92 { get; set; }="test";
        //public string p93 { get; set; }="test";
        //public string p94 { get; set; }="test";
        //public string p95 { get; set; }="test";
        //public string p96 { get; set; }="test";
        //public string p97 { get; set; }="test";
        //public string p98 { get; set; }="test";
        //public string p99 { get; set; }="test";
        //public string p100 { get; set; }="test";

    }
}
